USE [MP10]
GO

/****** Object:  Table [dbo].[SZ4010]    Script Date: 07/05/2010 16:23:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SZ4010](
	[Z4_FILIAL] [varchar](2) NOT NULL,
	[Z4_CODJOB] [varchar](9) NOT NULL,
	[Z4_VERSAO] [varchar](1) NOT NULL,
	[Z4_GRUPO] [varchar](1) NOT NULL,
	[Z4_EMISSAO] [varchar](8) NOT NULL,
	[Z4_CLIENTE] [varchar](6) NOT NULL,
	[Z4_LOJA] [varchar](2) NOT NULL,
	[Z4_STATUS] [varchar](1) NOT NULL,
	[Z4_PAI] [varchar](1) NOT NULL,
	[Z4_NUMPAI] [varchar](6) NOT NULL,
	[Z4_NUM] [varchar](6) NOT NULL,
	[Z4_USER] [varchar](30) NOT NULL,
	[D_E_L_E_T_] [varchar](1) NOT NULL,
	[R_E_C_N_O_] [int] NOT NULL,
	[R_E_C_D_E_L_] [int] NOT NULL,
	[Z4_BV] [float] NOT NULL,
 CONSTRAINT [SZ4010_PK] PRIMARY KEY CLUSTERED 
(
	[R_E_C_N_O_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_FILIAL_DF]  DEFAULT ('  ') FOR [Z4_FILIAL]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_CODJOB_DF]  DEFAULT ('         ') FOR [Z4_CODJOB]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_VERSAO_DF]  DEFAULT (' ') FOR [Z4_VERSAO]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_GRUPO_DF]  DEFAULT (' ') FOR [Z4_GRUPO]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_EMISSAO_DF]  DEFAULT ('        ') FOR [Z4_EMISSAO]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_CLIENTE_DF]  DEFAULT ('      ') FOR [Z4_CLIENTE]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_LOJA_DF]  DEFAULT ('  ') FOR [Z4_LOJA]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_STATUS_DF]  DEFAULT (' ') FOR [Z4_STATUS]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_PAI_DF]  DEFAULT (' ') FOR [Z4_PAI]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_NUMPAI_DF]  DEFAULT ('      ') FOR [Z4_NUMPAI]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_NUM_DF]  DEFAULT ('      ') FOR [Z4_NUM]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_USER_DF]  DEFAULT ('                              ') FOR [Z4_USER]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_D_E_L_E_T__DF]  DEFAULT (' ') FOR [D_E_L_E_T_]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_R_E_C_N_O__DF]  DEFAULT ((0)) FOR [R_E_C_N_O_]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_R_E_C_D_E_L__DF]  DEFAULT ((0)) FOR [R_E_C_D_E_L_]
GO

ALTER TABLE [dbo].[SZ4010] ADD  CONSTRAINT [SZ4010_Z4_BV_DF]  DEFAULT ((0)) FOR [Z4_BV]
GO


