USE [MP10]
GO

/****** Object:  Table [dbo].[SZ2010]    Script Date: 07/05/2010 16:22:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SZ2010](
	[Z2_FILIAL] [varchar](2) NOT NULL,
	[Z2_CODJOB] [varchar](9) NOT NULL,
	[Z2_VERSAO] [varchar](1) NOT NULL,
	[Z2_NUMZ4] [varchar](6) NOT NULL,
	[Z2_PAI] [varchar](1) NOT NULL,
	[Z2_ATIVO] [varchar](1) NOT NULL,
	[Z2_STATUS] [varchar](4) NOT NULL,
	[D_E_L_E_T_] [varchar](1) NOT NULL,
	[R_E_C_N_O_] [int] NOT NULL,
	[R_E_C_D_E_L_] [int] NOT NULL,
	[Z2_RESERVA] [varchar](3) NOT NULL,
 CONSTRAINT [SZ2010_PK] PRIMARY KEY CLUSTERED 
(
	[R_E_C_N_O_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_Z2_FILIAL_DF]  DEFAULT ('  ') FOR [Z2_FILIAL]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_Z2_CODJOB_DF]  DEFAULT ('         ') FOR [Z2_CODJOB]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_Z2_VERSAO_DF]  DEFAULT (' ') FOR [Z2_VERSAO]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_Z2_NUMZ4_DF]  DEFAULT ('      ') FOR [Z2_NUMZ4]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_Z2_PAI_DF]  DEFAULT (' ') FOR [Z2_PAI]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_Z2_ATIVO_DF]  DEFAULT (' ') FOR [Z2_ATIVO]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_Z2_STATUS_DF]  DEFAULT ('    ') FOR [Z2_STATUS]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_D_E_L_E_T__DF]  DEFAULT (' ') FOR [D_E_L_E_T_]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_R_E_C_N_O__DF]  DEFAULT ((0)) FOR [R_E_C_N_O_]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_R_E_C_D_E_L__DF]  DEFAULT ((0)) FOR [R_E_C_D_E_L_]
GO

ALTER TABLE [dbo].[SZ2010] ADD  CONSTRAINT [SZ2010_Z2_RESERVA_DF]  DEFAULT ('   ') FOR [Z2_RESERVA]
GO


