USE [MP10]
GO

/****** Object:  Table [dbo].[SZ5010]    Script Date: 07/05/2010 16:24:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SZ5010](
	[Z5_FILIAL] [varchar](2) NOT NULL,
	[Z5_ITEM] [varchar](2) NOT NULL,
	[Z5_PRODUTO] [varchar](15) NOT NULL,
	[Z5_UM] [varchar](2) NOT NULL,
	[Z5_QUANT] [float] NOT NULL,
	[Z5_PRECO] [float] NOT NULL,
	[Z5_TOTAL] [float] NOT NULL,
	[Z5_TES] [varchar](3) NOT NULL,
	[Z5_DESCPER] [float] NOT NULL,
	[Z5_DESCVAL] [float] NOT NULL,
	[Z5_NUMZ4] [varchar](6) NOT NULL,
	[Z5_OBS] [varchar](80) NOT NULL,
	[D_E_L_E_T_] [varchar](1) NOT NULL,
	[R_E_C_N_O_] [int] NOT NULL,
	[Z5_DESCR] [varchar](30) NOT NULL,
	[R_E_C_D_E_L_] [int] NOT NULL,
	[Z5_AREA] [varchar](30) NOT NULL,
	[Z5_NUMDIAS] [float] NOT NULL,
	[Z5_BV] [float] NOT NULL,
 CONSTRAINT [SZ5010_PK] PRIMARY KEY CLUSTERED 
(
	[R_E_C_N_O_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_FILIAL_DF]  DEFAULT ('  ') FOR [Z5_FILIAL]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_ITEM_DF]  DEFAULT ('  ') FOR [Z5_ITEM]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_PRODUTO_DF]  DEFAULT ('               ') FOR [Z5_PRODUTO]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_UM_DF]  DEFAULT ('  ') FOR [Z5_UM]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_QUANT_DF]  DEFAULT ((0)) FOR [Z5_QUANT]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_PRECO_DF]  DEFAULT ((0)) FOR [Z5_PRECO]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_TOTAL_DF]  DEFAULT ((0)) FOR [Z5_TOTAL]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_TES_DF]  DEFAULT ('   ') FOR [Z5_TES]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_DESCPER_DF]  DEFAULT ((0)) FOR [Z5_DESCPER]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_DESCVAL_DF]  DEFAULT ((0)) FOR [Z5_DESCVAL]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_NUMZ4_DF]  DEFAULT ('      ') FOR [Z5_NUMZ4]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_OBS_DF]  DEFAULT ('                                                                                ') FOR [Z5_OBS]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_D_E_L_E_T__DF]  DEFAULT (' ') FOR [D_E_L_E_T_]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_R_E_C_N_O__DF]  DEFAULT ((0)) FOR [R_E_C_N_O_]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_DESCR_DF]  DEFAULT ('                              ') FOR [Z5_DESCR]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_R_E_C_D_E_L__DF]  DEFAULT ((0)) FOR [R_E_C_D_E_L_]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_AREA_DF]  DEFAULT ('                              ') FOR [Z5_AREA]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_NUMDIAS_DF]  DEFAULT ((0)) FOR [Z5_NUMDIAS]
GO

ALTER TABLE [dbo].[SZ5010] ADD  CONSTRAINT [SZ5010_Z5_BV_DF]  DEFAULT ((0)) FOR [Z5_BV]
GO


