USE [MP10]
GO

/****** Object:  Table [dbo].[SZ3010]    Script Date: 07/05/2010 16:23:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SZ3010](
	[Z3_FILIAL] [varchar](2) NOT NULL,
	[Z3_CODJOB] [varchar](9) NOT NULL,
	[Z3_ORCADO] [varchar](1) NOT NULL,
	[Z3_ORCALT] [varchar](1) NOT NULL,
	[Z3_ORCOBS] [image] NULL,
	[Z3_ITEM] [varchar](5) NOT NULL,
	[Z3_ORCPROD] [varchar](15) NOT NULL,
	[Z3_ORCQT] [float] NOT NULL,
	[Z3_TECPROD] [varchar](15) NOT NULL,
	[Z3_TECQT] [float] NOT NULL,
	[Z3_TECOBS] [image] NULL,
	[D_E_L_E_T_] [varchar](1) NOT NULL,
	[R_E_C_N_O_] [int] NOT NULL,
	[R_E_C_D_E_L_] [int] NOT NULL,
	[Z3_RESERVA] [varchar](3) NOT NULL,
 CONSTRAINT [SZ3010_PK] PRIMARY KEY CLUSTERED 
(
	[R_E_C_N_O_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_FILIAL_DF]  DEFAULT ('  ') FOR [Z3_FILIAL]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_CODJOB_DF]  DEFAULT ('         ') FOR [Z3_CODJOB]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_ORCADO_DF]  DEFAULT (' ') FOR [Z3_ORCADO]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_ORCALT_DF]  DEFAULT (' ') FOR [Z3_ORCALT]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_ITEM_DF]  DEFAULT ('     ') FOR [Z3_ITEM]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_ORCPROD_DF]  DEFAULT ('               ') FOR [Z3_ORCPROD]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_ORCQT_DF]  DEFAULT ((0)) FOR [Z3_ORCQT]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_TECPROD_DF]  DEFAULT ('               ') FOR [Z3_TECPROD]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_TECQT_DF]  DEFAULT ((0)) FOR [Z3_TECQT]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_D_E_L_E_T__DF]  DEFAULT (' ') FOR [D_E_L_E_T_]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_R_E_C_N_O__DF]  DEFAULT ((0)) FOR [R_E_C_N_O_]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_R_E_C_D_E_L__DF]  DEFAULT ((0)) FOR [R_E_C_D_E_L_]
GO

ALTER TABLE [dbo].[SZ3010] ADD  CONSTRAINT [SZ3010_Z3_RESERVA_DF]  DEFAULT ('   ') FOR [Z3_RESERVA]
GO


